<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-U2N6T7R7" failures="2" tests="15" name="org.rerun.AutomationReRunMethod1" time="0.086" errors="0" timestamp="08 Apr 2024 07:36:54 GMT" skipped="10">
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc2" time="0.006">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc4" time="0.000">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.rerun.AutomationReRunMethod1.tc4(AutomationReRunMethod1.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc4 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc4" time="0.002">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc4" time="0.000">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc4" time="0.000">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc4" time="0.000">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc2" time="0.000">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc2" time="0.016">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc2" time="0.000">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc3" time="0.016"/>
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc5" time="0.016"/>
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc1" time="0.015"/>
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc4" time="0.000">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc2" time="0.000">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.rerun.AutomationReRunMethod1.tc2(AutomationReRunMethod1.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase classname="org.rerun.AutomationReRunMethod1" name="tc2" time="0.015">
    <skipped/>
  </testcase> <!-- tc2 -->
</testsuite> <!-- org.rerun.AutomationReRunMethod1 -->
